test:
  extends:
    file: base.yml
    service: base
  container_name: layer-test
  environment:
    NODE_ENV: test
    CT_URL: http://mymachine:9000
    API_VERSION: v1
  command: test
  links:
    - mongo

mongo:
  image: mongo:3.4
  command: --smallfiles
  ports:
    - "27017"
  restart: always
