version: "3"
services:
  develop:
    build: .
    ports:
      - "6000:6000"
    container_name: layer
    environment:
      PORT: 6000
      NODE_PATH: app/src
      CT_REGISTER_MODE: auto
      CT_URL: http://mymachine:9000
      LOCAL_URL: http://mymachine:6000
      CT_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
      API_VERSION: v1
      FASTLY_ENABLED: "false"
    command: develop
    links:
      - mongo
    volumes:
      - ./app:/opt/layer/app

  mongo:
    image: mongo:3.4
    container_name: layer-mongo-develop
    command: --smallfiles
    ports:
      - "27017"
    volumes:
      - $HOME/docker/data/layer:/data/db
